= NLP - Part of Speech Tagging
:toc:
:toc-title: Contents
:toclevels: 4
:nofooter:
:stem: latexmath

== PoS Tagging definition

The assignment of a lexical category to a word

* stem:[f(w) \rightarrow L]
* noun, verb, adverb, etc

The lexical category depends on the context in which the word appears

* a word might act as a noun or verb depending on where it is in a sentence

Categories don't have to come from grammatical rules

* can be medication name, disease name, patient status codes
* not necessarily nouns/verbs etc

=== Why PoS tagging?

It's the first step of *traditional* syntactic analysis

* we have to know what a sentence is made of before we can move on
* LLMs don't do this because they have 4138473298 morbillion parameters so they hope to God that they generate something correct

PoS assumes that words work in a certain way and that words in the same category are interchangeable

* substituting a noun with another noun will produce a correct sentence
* it may be meaningless but the structure will be correct

PoS tagging can also be used for lemmatization

* avoids confusing things like adverbs

== Word classes

Words can be divided into 2 overall classes

=== Closed classes

Fixed words that act as glue

* i.e. words that chain other words together
* and, but, the, at, this, under, over

. Prepositions
. Determiners
. Conjunctions
. Pronouns

=== Open Classes

Words we actually use in the real world

* no real fixed set
* new words come out every day
** *neologisms* and technical jargon especially

=== Tag sets

A tagset is an encoding of word classes

Ideally we have a distinct set of abbreviators

* NN
* ADJ

==== Penn Treebank

Largest english tag set

* only works for english
* low granularity for other languages

36 pos tags and 12 other tags

Like:

* DT -> determinants
* CC -> coordinative conjunctions
** and, or
* JJ -> adjective
** JJR -> comparative adjective
** JJS -> superlative adjective
* NN -> noun
** NNS -> plural noun
** NNP -> proper noun

=== Universal Dependencies

More modern than tag sets

Works across languages

17 linguistically consistent classes

* they work in English and Western Sumatran etc
* not all languages are covered but close enough
* less granular than Penn Treebank

3 classes:

. open words
* 6 open words
. closed words
* 8 open words
. other
* 3 types
** punctuation
** symbols
** everything else

==== UD features

To make up for low granularity UD adds new features

* like a dictionary of attribute=value for each tag
* like verbs and reflexive verbs 
** VERB(Reflex)

3 classes of features:

* lexical
* inflectional
* other

Categories are added if the feature appears in at least 2 different languages

== How PoS?

Many challenges but *lexical ambiguity* is the biggest

=== Lexical ambiguity

The same word can have different meanings depending on the context

Happens constantly and across languages

Finding the right tag is extremely hard

* the tag of a word depends on the tags of surrounding words (*local syntax*)
* it's like a dog chasing its own tail

=== Medical Domain challenges

Medical language is a form of a technical jargon where words don't always mean what we expect and new words are made constantly

* if you know you are producing language for a doctor you can assume that they are familiar with the jargon

Medical language is full of abbreviations

* extremely hard to parse unless you know the abbreviations too

There are documents that collect domain specific terms called *gazeteers*

* in this case *medical* gazeteers
* they aren't always up to date but they exist

== Symbolic and statistical tagging

=== Symbolic approaches

Simple rule based programs

* if this then that

Tools like

* Brill tagger (1992)
** transformation based
** very brittle
** adding a new exceptional case may break some other transformation
* Regex
** finds patterns and maps them to symbols

=== Probabilistic Approaches

Model the sequence as a sequence of states

Use a Markov chain to determine the tag of the next word

* if tag[2] == adjective then tag[1] == noun

We find the sequence of tags with the highest probabilty for a given sequence of words

==== HMM

Tags are hidden states

Transitions are probabilities of finding a tag given the previous tag

Emissions are the probability of the word wi produced by tag i

HMMs are very interpretable

* trace the matrix

HMMs have a few limitations:

We don't only use words

* lemmas
* stems

Words change meaning depending on spelling and other structural differences

* uppercase words
* word forms
** like in arabic

Other algorithmic limitations include:

* generative constraints
* independence assumptions
* label bias problems

==== Generative Markov Models

Use the chain rule and the Markov assumption to do something

CAUTION: the number of probabilties become really small

Emission probabilities are estimated by counting how often a tag is associated with that word in the corpus

* ~n_words * 40 matrix
* of very small numbers

Transition probabilities are estimated by counting how often a tag ti follows tag ti-1 in the corpus

* ~40x40 matrix

These are only feasible if the corpus is annotated

==== Viterbi Algorithm

The number of possible sequences grows exponentially

* p^n
** n are number of words
** p is the number of tags

Viterbi algorithm uses dynamic programming 

* stores the best sub path at each word step
* np^2 complexity

Requires 2 matrices:

* transition
* emission
** estimated from corpus

Requires the set of possible hidden states and the sequence of observations

Uses a special tag to define the initial state

Returns the most probable parth across hidden states

* i.e. sequence of tags with highest probability

==== Conditional Random Fields

CRFs are disciminative and not generative

* they don't compute the probability of tag word pairs from estimations

Pairs are computed by arbitrarily computed rule sets

* features (functions) are typically built manually

Like:

. is the word capitalized and is the previous tag a noun?
. does the word end in -itis?
. is the word in a medical dictionary?

CAUTION: functions are not necessarily probabilities. They can be counts or other stuff

== Neural Approaches

=== Bi-LSTMs

LSTMs that analyze a sequence in both directions

* forward context
* backward context

Works well because languages are inextricably linked to time

* we parse things one after the other
* not in a matrix format

Often used with CRFs to determine whether certain properties are correct

=== Transformers

Can process long sentences in parallel

* multiple bits are processed at the same time
* they sample the sentence in multiple points
* uses attention to determine importance

==== Contextualized tagging

Models like BioBERT and ClinicalBERT take into account domain specific PoS patterns

* they are trained on scientific literature

CAUTION: scientific literature is not the same as real medical notes

Document context is important but very hard to do

* if lead is in toxicology report -> metal poisoning
* if lead is in HR report -> verb/role

LLMs use windowed attention to resolve this across sentences


== Tools

=== NLTK

Old and tested


By default uses *averaged perceptron* for tagging

Trained on general news

* won't generalize well to medical terms

=== SpaCY

More modern

Uses either:

* Multitask CNN
* Transformer

Works well for single strings

* has single exposed method that does everything

==== sciSpaCY

Same model but tuned for biomedical literature

==== medSpaCY

Same model but trained on medical terminology

=== Stanza

Very small

Based on bi-LSTM

Has specific biomedical models

* not very in depth but still

Pipeline based programming
