= Bioinformatics and Systems Biology - Pharmacophore Based Drug Design
:toc:
:toc-title: Contents
:nofooter:
:stem: latexmath

== What is a pharmacophore?

Creating a model of new molecules with certain biological features

3D space arrangement of chemical features required for the molecule to interact with biological compound

* specific pharmacophore features
* represented by spheres


This is done by basing new compounds on known compounds with the following characteristics:

* same mechanism of action
** they work the same
* same receptor
** they bind to the same structure (macromolecule)
* same binding site
** they have the same attachment points

.Pseudocode example
[source,python]
----
known_molecule = molecules[0]
new_molecule = molecules[-1]

mimic = False

if new_molecule.action == known_molecule.action:
    if new_molecule.receptor == known_molecule.receptor:
        if new_molecule.binding_site = known_molecule.binding_site:
            mimic = True
----

This should produce a *pharmacophore*

=== Molecular mimicry

Mimicking structural features of a reference compound is called *molecular mimicry*

How do we know which elements to mimic?

* not all elements are essential
* some are not essential
** most non essential elements are required to maintain the molecule's shape

Given this new information we can update the definition of pharmacophore:

* "*A pharmacophore can be defined as a specific 3D arrangement of chemical groups common to active molecules and essential for their biological activity*"

== How does it work?

. Collect data
* Gather information from multiple sources about molecules of interest
* paper P found that molecule X is active against our target
* different paper found molecule H that is also active against our target with other properties
. Analyze data
* Create a framework that integrates knowledge about:
** essential structural elements
** sterochemical features of the binding site
. Design new molecules
* Create new molecules with the properties we identified during analysis
* Modify molecule X -> molecule Y
* Modify molecule H -> Molecule Y2
** X and H may be patented so beware

=== Simple example

Consider *Molecule A* and *Molecule B*

* structurally dissimilar
* both active against some target *T*
* we know their bioactive conformation
** we know how they interact with *T*'s binding site

.Steps

3D x-ray structure is required

. Superimpose A and B
* A binds to the receptor in conformation CA
* B binds to the receptor in conformation CB
** this shows common conformational features
** e.g. both have 3 aromatic rings and all 3 rings are in the same arrangement in both molecules
. Take common features
* in our case these would be the 3 aromatic rings
. Find molecules with similar features
* molecules with 3 aromatic rings with the same arrangement as A and B


.What if you don't have the 3D x-ray structure?

* pairwise alignment of each conformation of both molecules
* find the superposition with the best alignment of certain parts of the molecules
* there can be multiple solutions that need to be tested later

== Receptor-based pharmacophore

If you have a complex (receptor+ligand) you can interpret their interactions

* this can be used to construct structure-based pharmacophore models

These models take into account:

* complementarity of chemical characteristics
** how the chemical composition differs
* spatial complementarity
** how their spatial arrangement differs

=== Case Study - MbtI

Kill enzyme that helps tuberculosis bacteria consume iron ions

Kill enzyme -> no iron ions -> bacterium dies

Filter 1.5m complexes -> 2k complexes with the required features

* need to use HTS for this
* far too many molecules/complexes to do manually
** make the robot do it
* HTS is stupid expensive
** database with 100k compounds ~> 500k euro

HTS outputs are noisy

* many false positives
* many false negatives
* true positives don't tell you how the interaction happens

* Use docking

Many docking softwares

* which do you use?

Use multiple docking softwares and compare the results

* if 9/10 docking softwares predict the same ligand pose then that pose is more likely to be real

This is *consensus docking*

== Consensus docking

Docking sofwares will almost never produce perfectly identical results

* one might produce a molecule that is rotated about the X axis by 0.5 degrees
* another might produce another that requires an extra hydrogen bond

So we have to use fuzzier similarity methods

Assume we have stem:[n] docking softwares that each produce stem:[p] poses

* compute RMSD between the poses generated by each docking software
** matrix arrangement

The final consensus level is determined by how many RMSDs are below/above some threshold (e.g. 2 Angstrom)

* higher = better
** means more softwares agree on the same general pose

[source,python]
----
RMSDS = compute_rmsd(poses)

THRESHOLD = 2

def consensus(rmsds, threshold) -> float:
    if all(rmsd < threshold for rmsd in rmsds):
        return len(rmsds)
    elif all(rmsd > threshold for rmsd in rmsds):
        return 1
    else:
        return sum(filter(lambda f: f < threshold, rmsds))
----

