name: GitHub Pages Publish

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # <-- Add this line to grant write permission
      pages: write     # <-- Required for GitHub Pages deployment
      id-token: write  # <-- Required for GitHub Pages deployment

    steps:
      - uses: actions/checkout@v3

      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          pdf_build: true
          # asciidoctor_params: --attribute=nofooter
          # adoc_file_ext: .ascii
          # source_dir: docs/
          # slides_build: true
          # pre_build:
          # post_build:
